# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/lzh/Desktop/cpp_http_server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/lzh/Desktop/cpp_http_server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lzh/Desktop/cpp_http_server/CMakeFiles /home/lzh/Desktop/cpp_http_server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/lzh/Desktop/cpp_http_server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named http_sever

# Build rule for target.
http_sever: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 http_sever
.PHONY : http_sever

# fast build rule for target.
http_sever/fast:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/build
.PHONY : http_sever/fast

src/Connection.o: src/Connection.cpp.o

.PHONY : src/Connection.o

# target to build an object file
src/Connection.cpp.o:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/Connection.cpp.o
.PHONY : src/Connection.cpp.o

src/Connection.i: src/Connection.cpp.i

.PHONY : src/Connection.i

# target to preprocess a source file
src/Connection.cpp.i:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/Connection.cpp.i
.PHONY : src/Connection.cpp.i

src/Connection.s: src/Connection.cpp.s

.PHONY : src/Connection.s

# target to generate assembly for a file
src/Connection.cpp.s:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/Connection.cpp.s
.PHONY : src/Connection.cpp.s

src/EventLoop.o: src/EventLoop.cpp.o

.PHONY : src/EventLoop.o

# target to build an object file
src/EventLoop.cpp.o:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/EventLoop.cpp.o
.PHONY : src/EventLoop.cpp.o

src/EventLoop.i: src/EventLoop.cpp.i

.PHONY : src/EventLoop.i

# target to preprocess a source file
src/EventLoop.cpp.i:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/EventLoop.cpp.i
.PHONY : src/EventLoop.cpp.i

src/EventLoop.s: src/EventLoop.cpp.s

.PHONY : src/EventLoop.s

# target to generate assembly for a file
src/EventLoop.cpp.s:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/EventLoop.cpp.s
.PHONY : src/EventLoop.cpp.s

src/HttpRequest.o: src/HttpRequest.cpp.o

.PHONY : src/HttpRequest.o

# target to build an object file
src/HttpRequest.cpp.o:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/HttpRequest.cpp.o
.PHONY : src/HttpRequest.cpp.o

src/HttpRequest.i: src/HttpRequest.cpp.i

.PHONY : src/HttpRequest.i

# target to preprocess a source file
src/HttpRequest.cpp.i:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/HttpRequest.cpp.i
.PHONY : src/HttpRequest.cpp.i

src/HttpRequest.s: src/HttpRequest.cpp.s

.PHONY : src/HttpRequest.s

# target to generate assembly for a file
src/HttpRequest.cpp.s:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/HttpRequest.cpp.s
.PHONY : src/HttpRequest.cpp.s

src/HttpResponse.o: src/HttpResponse.cpp.o

.PHONY : src/HttpResponse.o

# target to build an object file
src/HttpResponse.cpp.o:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/HttpResponse.cpp.o
.PHONY : src/HttpResponse.cpp.o

src/HttpResponse.i: src/HttpResponse.cpp.i

.PHONY : src/HttpResponse.i

# target to preprocess a source file
src/HttpResponse.cpp.i:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/HttpResponse.cpp.i
.PHONY : src/HttpResponse.cpp.i

src/HttpResponse.s: src/HttpResponse.cpp.s

.PHONY : src/HttpResponse.s

# target to generate assembly for a file
src/HttpResponse.cpp.s:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/HttpResponse.cpp.s
.PHONY : src/HttpResponse.cpp.s

src/Logger.o: src/Logger.cpp.o

.PHONY : src/Logger.o

# target to build an object file
src/Logger.cpp.o:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/Logger.cpp.o
.PHONY : src/Logger.cpp.o

src/Logger.i: src/Logger.cpp.i

.PHONY : src/Logger.i

# target to preprocess a source file
src/Logger.cpp.i:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/Logger.cpp.i
.PHONY : src/Logger.cpp.i

src/Logger.s: src/Logger.cpp.s

.PHONY : src/Logger.s

# target to generate assembly for a file
src/Logger.cpp.s:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/Logger.cpp.s
.PHONY : src/Logger.cpp.s

src/Server.o: src/Server.cpp.o

.PHONY : src/Server.o

# target to build an object file
src/Server.cpp.o:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/Server.cpp.o
.PHONY : src/Server.cpp.o

src/Server.i: src/Server.cpp.i

.PHONY : src/Server.i

# target to preprocess a source file
src/Server.cpp.i:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/Server.cpp.i
.PHONY : src/Server.cpp.i

src/Server.s: src/Server.cpp.s

.PHONY : src/Server.s

# target to generate assembly for a file
src/Server.cpp.s:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/Server.cpp.s
.PHONY : src/Server.cpp.s

src/ThreadPool.o: src/ThreadPool.cpp.o

.PHONY : src/ThreadPool.o

# target to build an object file
src/ThreadPool.cpp.o:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/ThreadPool.cpp.o
.PHONY : src/ThreadPool.cpp.o

src/ThreadPool.i: src/ThreadPool.cpp.i

.PHONY : src/ThreadPool.i

# target to preprocess a source file
src/ThreadPool.cpp.i:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/ThreadPool.cpp.i
.PHONY : src/ThreadPool.cpp.i

src/ThreadPool.s: src/ThreadPool.cpp.s

.PHONY : src/ThreadPool.s

# target to generate assembly for a file
src/ThreadPool.cpp.s:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/ThreadPool.cpp.s
.PHONY : src/ThreadPool.cpp.s

src/Timer.o: src/Timer.cpp.o

.PHONY : src/Timer.o

# target to build an object file
src/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/Timer.cpp.o
.PHONY : src/Timer.cpp.o

src/Timer.i: src/Timer.cpp.i

.PHONY : src/Timer.i

# target to preprocess a source file
src/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/Timer.cpp.i
.PHONY : src/Timer.cpp.i

src/Timer.s: src/Timer.cpp.s

.PHONY : src/Timer.s

# target to generate assembly for a file
src/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/Timer.cpp.s
.PHONY : src/Timer.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/http_sever.dir/build.make CMakeFiles/http_sever.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... http_sever"
	@echo "... src/Connection.o"
	@echo "... src/Connection.i"
	@echo "... src/Connection.s"
	@echo "... src/EventLoop.o"
	@echo "... src/EventLoop.i"
	@echo "... src/EventLoop.s"
	@echo "... src/HttpRequest.o"
	@echo "... src/HttpRequest.i"
	@echo "... src/HttpRequest.s"
	@echo "... src/HttpResponse.o"
	@echo "... src/HttpResponse.i"
	@echo "... src/HttpResponse.s"
	@echo "... src/Logger.o"
	@echo "... src/Logger.i"
	@echo "... src/Logger.s"
	@echo "... src/Server.o"
	@echo "... src/Server.i"
	@echo "... src/Server.s"
	@echo "... src/ThreadPool.o"
	@echo "... src/ThreadPool.i"
	@echo "... src/ThreadPool.s"
	@echo "... src/Timer.o"
	@echo "... src/Timer.i"
	@echo "... src/Timer.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

